// src/components/ObjectProperties.tsx
import React from 'react';
import { type Entity } from '../ecs';

interface ObjectPropertiesProps {
    selectedEntity: Entity;
    setSelectedEntity: (ent: Entity | null) => void;
    onDelete: (ent: Entity) => void;
}

export const ObjectProperties: React.FC<ObjectPropertiesProps> = ({ selectedEntity, setSelectedEntity, onDelete }) => {
    const update = () => setSelectedEntity({ ...selectedEntity });
    const body = selectedEntity.physicsBody || selectedEntity.staticBody;

    return (
        <div style={{ flex: 1, padding: 12, fontSize: 12, overflowY: 'auto', borderTop: '1px solid #333' }}>
            <div style={{ fontSize: 10, marginBottom: 15, color: '#555', letterSpacing: '1px' }}>PROPERTIES</div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <span>Name</span>
                    <input value={selectedEntity.name} onChange={e => { selectedEntity.name = e.target.value; update(); }} style={{ width: 110, background: '#000', color: '#fff', border: '1px solid #333', padding: '4px 6px' }}/>
                </div>

                {selectedEntity.transform && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                        <span>Position</span>
                        <div style={{ display: 'flex', gap: 4 }}>
                            <input type="number" step="0.1" value={selectedEntity.transform.position[0]} onChange={e => { selectedEntity.transform!.position[0] = Number(e.target.value); update(); }} style={{ width: 50, background: '#000', color: '#fff' }}/>
                            <input type="number" step="0.1" value={selectedEntity.transform.position[1]} onChange={e => { selectedEntity.transform!.position[1] = Number(e.target.value); update(); }} style={{ width: 50, background: '#000', color: '#fff' }}/>
                        </div>
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                            <span>Rotation</span>
                            <input type="number" step="1" value={Math.round(selectedEntity.transform.rotation * (180/Math.PI))} onChange={e => { selectedEntity.transform!.rotation = Number(e.target.value) * (Math.PI/180); update(); }} style={{ width: 60, background: '#000', color: '#fff' }}/>
                        </div>
                    </div>
                )}

                {body && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8, padding: '8px', background: '#222', borderRadius: 4 }}>
                        {selectedEntity.physicsBody && (
                            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                                <span>Mass</span>
                                <input type="number" min="0.1" step="0.1" value={selectedEntity.physicsBody.mass} onChange={e => { selectedEntity.physicsBody!.mass = Number(e.target.value); update(); }} style={{ width: 60, background: '#111', color: '#fff' }}/>
                            </div>
                        )}
                        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                            <span>Friction</span>
                            <input type="number" min="0" max="1" step="0.05" value={body.friction} onChange={e => { body.friction = Number(e.target.value); update(); }} style={{ width: 60, background: '#111', color: '#fff' }}/>
                        </div>
                    </div>
                )}

                {selectedEntity.sdfCollider && (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                        <span>SDF Params</span>
                        {Array.from(selectedEntity.sdfCollider.parameters).map((p, i) => (
                            <div key={i} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                                <span style={{ fontSize: 9, color: '#666' }}>Param {i}</span>
                                <input type="number" step="0.1" value={p} onChange={e => { selectedEntity.sdfCollider!.parameters[i] = Number(e.target.value); update(); }} style={{ width: 60, background: '#000', color: '#fff' }}/>
                            </div>
                        ))}
                    </div>
                )}

                <button onClick={() => onDelete(selectedEntity)} style={{ marginTop: 20, background: '#aa3333', color: '#fff', border: 'none', padding: '10px', cursor: 'pointer', fontWeight: 'bold' }}>DELETE OBJECT</button>
            </div>
        </div>
    );
};

// src/gui/components/ObjectProperties.vue
<script setup lang="ts">
import { type Entity } from '@/ecs';
import { computed } from 'vue';

const props = defineProps<{
  selectedEntity: Entity;
}>();

const emit = defineEmits<{
  (e: 'update'): void;
  (e: 'delete', entity: Entity): void;
}>();

const body = computed(() => props.selectedEntity.physicsBody || props.selectedEntity.staticBody);

const update = () => {
  emit('update');
};

const radToDeg = (rad: number) => Math.round(rad * (180 / Math.PI));
const degToRad = (deg: number) => deg * (Math.PI / 180);

const rotationDeg = computed({
  get: () => props.selectedEntity.transform ? radToDeg(props.selectedEntity.transform.rotation) : 0,
  set: (val: number) => {
    if (props.selectedEntity.transform) {
      props.selectedEntity.transform.rotation = degToRad(val);
      update();
    }
  }
});
</script>

<template>
  <div>
    <div>
      Properties
    </div>

    <div>
      <!-- General -->
      <UFormGroup label="Name" size="xs">
        <UInput 
          v-model="selectedEntity.name" 
          @update:model-value="update"
          size="xs"
          autocomplete="off"
        />
      </UFormGroup>

      <!-- Transform -->
      <div v-if="selectedEntity.transform">
        <div>Transform</div>
        
        <UFormGroup label="Position" size="xs">
          <div>
            <UInput 
              type="number" 
              step="0.1" 
              v-model.number="selectedEntity.transform.position[0]" 
              @update:model-value="update"
              size="xs"
             
              placeholder="X"
            >
              <template #leading>
                <span>X</span>
              </template>
            </UInput>
            <UInput 
              type="number" 
              step="0.1" 
              v-model.number="selectedEntity.transform.position[1]" 
              @update:model-value="update"
              size="xs"
             
              placeholder="Y"
            >
              <template #leading>
                <span>Y</span>
              </template>
            </UInput>
          </div>
        </UFormGroup>

        <UFormGroup label="Rotation" size="xs">
          <UInput 
            type="number" 
            v-model.number="rotationDeg" 
            size="xs"
          >
            <template #trailing>
              <span>°</span>
            </template>
          </UInput>
        </UFormGroup>
      </div>

      <!-- Physics -->
      <div v-if="body">
        <div>Physics</div>
        
        <UFormGroup v-if="selectedEntity.physicsBody" label="Mass" size="xs">
          <UInput 
            type="number" 
            min="0.1" 
            step="0.1" 
            v-model.number="selectedEntity.physicsBody.mass" 
            @update:model-value="update"
            size="xs"
          />
        </UFormGroup>

        <UFormGroup label="Friction" size="xs">
          <UInput 
            type="number" 
            min="0" 
            max="1" 
            step="0.05" 
            v-model.number="body.friction" 
            @update:model-value="update"
            size="xs"
          />
        </UFormGroup>
      </div>

      <!-- SDF Collider -->
      <div v-if="selectedEntity.sdfCollider">
        <div>SDF Collider</div>
        
        <UFormGroup 
          v-for="(p, i) in selectedEntity.sdfCollider.parameters" 
          :key="i" 
          :label="`Param ${i}`" 
          size="xs"
        >
          <UInput 
            type="number" 
            step="0.1" 
            v-model.number="selectedEntity.sdfCollider.parameters[i]" 
            @update:model-value="update"
            size="xs"
          />
        </UFormGroup>
      </div>

      <UDivider />

      <UButton
        @click="emit('delete', selectedEntity)"
        color="red"
        variant="soft"
        block
        icon="i-heroicons-trash"
        size="xs"
      >
        Delete Object
      </UButton>
    </div>
  </div>
</template>
