// src/gui/views/PlayerView.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { PlayerEngine } from '@/core/PlayerEngine';

const props = defineProps<{
  levelName: string;
}>();

const canvasRef = ref<HTMLDivElement | null>(null);
const fps = ref(0);
const engine = ref<PlayerEngine | null>(null);

onMounted(async () => {
  if (!canvasRef.value) return;
  
  const player = new PlayerEngine(canvasRef.value);
  player.onFpsUpdate = (val) => fps.value = val;
  
  try {
    await player.init();
    await player.spawnPlayer();
    engine.value = player;
  } catch (err) {
    console.error('Failed to initialize PlayerEngine:', err);
  }
});

onUnmounted(() => {
  if (engine.value) {
    engine.value.dispose();
  }
});
</script>

<template>
  <div class="h-screen w-screen bg-black overflow-hidden relative">
    <div ref="canvasRef" class="w-full h-full" />
    <div class="absolute top-4 left-4 text-white opacity-50 pointer-events-none text-xs font-mono">
      {{ fps }} FPS
    </div>
  </div>
</template>

// src/views/PlayerView.tsx
import React, { useEffect, useRef, useState } from 'react';
import { PlayerEngine } from '../core/PlayerEngine';

export const PlayerView: React.FC<{ levelName: string }> = ({ levelName }) => {
    const canvasRef = useRef<HTMLDivElement>(null);
    const [fps, setFps] = useState(0);

    useEffect(() => {
        if (!canvasRef.current) return;
        const player = new PlayerEngine(canvasRef.current);
        player.onFpsUpdate = setFps;
        player.init().then(() => player.spawnPlayer()).catch(console.error);
        return () => player.dispose();
    }, [levelName]);

    return (
        <div style={{ width: '100%', height: '100%', position: 'relative', background: '#000' }}>
            <div ref={canvasRef} style={{ width: '100%', height: '100%', overflow: 'hidden' }} />
            <div style={{ position: 'absolute', top: 10, left: 10, color: '#444', fontSize: 12, zIndex: 10 }}>
                FPS: {fps} | PLAYER MODE
            </div>
        </div>
    );
};
